name: CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: wuzzeb/action-setup@master
        id: pnpmsetup

      - run: echo "${ steps.pnpmsetup.outputs.bin_dest }"

      - run: pnpm --version

